// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rlrkvovudmlbtlbktvsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJscmt2b3Z1ZG1sYnRsYmt0dnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTkzOTIsImV4cCI6MjA2ODMzNTM5Mn0.FskBuZ1viUt_WPUZ4ctIF0NfHd7euyZDrIhXR_ZRcOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});